name: Build and test the develop branch

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      Solution_Name: NetFinance.sln
      Test_Project_Path: Tests/Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: develop
        fetch-depth: 0 

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build project
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore
      
    - name: Print AlphaVantage API Key1
      run: echo "AlphaVantage API Key is ${{ secrets.NET_FINANCE_CONFIGURATION__ALPHAVANTAGE_API_KEY }}"
            
    - name: Print AlphaVantage API Key2
      run: echo "AlphaVantage API Key is ${{ secrets.FOO }}"
            
            
    - name: Set environment variable from GitHub Secret
      run: |
        echo "NET_FINANCE_CONFIGURATION__ALPHAVANTAGE_API_KEY=MyValue1" >> $GITHUB_ENV
        echo "NetFinanceConfiguration__AlphaVantageApiKey=MyValue2" >> $GITHUB_ENV
        echo "AlphaVantageApiKey=MyValue3" >> $GITHUB_ENV
        echo "FOO=MyValue4" >> $GITHUB_ENV
      shell: bash

    - name: Print AlphaVantage API Key
      run: echo "AlphaVantage API Key is ${{ env.NET_FINANCE_CONFIGURATION__ALPHAVANTAGE_API_KEY }}"

    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration Release --no-restore
      env:
          NetFinanceConfiguration__AlphaVantageApiKey: xxxxxxxxxxxxxxxxxx

    - name: Run Tests and Generate Coverage Report
      run: |
        dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults
        reportgenerator -reports:./TestResults/**/coverage.cobertura.xml -targetdir:./TestResults/Coverage -reporttypes:Html

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./TestResults/Coverage  